export const defaultTheme = () => {
  localStorage.clear()
  localStorage.setItem('white', '#FFF')
  localStorage.setItem('lightGrayOpacity', '#a7a7a7ab')
  localStorage.setItem('lightGray', '#a7a7a7')
  localStorage.setItem('veryLightGray', '#E7E7E7')
  localStorage.setItem('gray', '#747778')
  localStorage.setItem('darkGray', '#676363')
  localStorage.setItem('red', '#CC2727')
  localStorage.setItem('transparentBrown', '#6b451ee6')
  localStorage.setItem('veryLightBrown', '#ce9f6e')
  localStorage.setItem('lightBrown', '#977452')
  localStorage.setItem('veryDarkBrown', '#240f04')
  localStorage.setItem('brown', '#6b451e')
  localStorage.setItem('black', '#000')
  localStorage.setItem('blackOpacity', '#0000004D')
}

export const colorblindTheme = () => {
  localStorage.clear()
  //   localStorage.setItem('white', '#000')
  //   localStorage.setItem('lightGrayOpacity', '#000')
  //   localStorage.setItem('lightGray', '#000')
  //   localStorage.setItem('veryLightGray', '#000')
  //   localStorage.setItem('gray', '#000')
  //   localStorage.setItem('darkGray', '#000')
  //   localStorage.setItem('red', '#000')
  //   localStorage.setItem('transparentBrown', '#000')
  //   localStorage.setItem('veryLightBrown', '#000')
  //   localStorage.setItem('lightBrown', '#000')
  //   localStorage.setItem('veryDarkBrown', '#FFF')
  //   localStorage.setItem('brown', '#FFF')
  //   localStorage.setItem('black', '#FFF')
  //   localStorage.setItem('blackOpacity', '#FFF')
}
