export const defaultColorSchema = () => {
  localStorage.clear()
  localStorage.setItem('colorSchemaEnum', '0')
  localStorage.setItem('white', '#FFF')
  localStorage.setItem('lightGrayOpacity', '#a7a7a7ab')
  localStorage.setItem('veryLightGray', '#E7E7E7')
  localStorage.setItem('lightGray', '#a7a7a7')
  localStorage.setItem('gray', '#747778')
  localStorage.setItem('darkGray', '#676363')
  localStorage.setItem('red', '#CC2727')
  localStorage.setItem('transparentBrown', '#6b451ee6')
  localStorage.setItem('veryLightBrown', '#ce9f6e')
  localStorage.setItem('lightBrown', '#977452')
  localStorage.setItem('brown', '#6b451e')
  localStorage.setItem('veryDarkBrown', '#240f04')
  localStorage.setItem('blackOpacity', '#0000004D')
  localStorage.setItem('black', '#000')
  location.reload()
}

export const grayColorSchema = () => {
  localStorage.clear()
  localStorage.setItem('colorSchemaEnum', '1')
  localStorage.setItem('white', '#FFF')
  localStorage.setItem('lightGrayOpacity', '#a7a7a7ab')
  localStorage.setItem('veryLightGray', '#dcdcdc')
  localStorage.setItem('lightGray', '#a7a7a7')
  localStorage.setItem('gray', '#747778')
  localStorage.setItem('darkGray', '#676363')
  localStorage.setItem('red', '#CC2727')
  localStorage.setItem('transparentBrown', '#454545')
  localStorage.setItem('veryLightBrown', '#c0c0c0')
  localStorage.setItem('lightBrown', '#977452')
  localStorage.setItem('brown', '#565656')
  localStorage.setItem('veryDarkBrown', '#240f04')
  localStorage.setItem('blackOpacity', '#0000004D')
  localStorage.setItem('black', '#000')
  location.reload()
}
